from __future__ import annotations

import html
from io import BytesIO
from pathlib import Path

import fitz

from app.models import ReportResponse


def _wrap_lines(text: str, max_chars: int = 90) -> str:
    words = text.split()
    lines: list[str] = []
    current: list[str] = []
    length = 0
    for word in words:
        if length + len(word) + 1 > max_chars and current:
            lines.append(" ".join(current))
            current = [word]
            length = len(word)
        else:
            current.append(word)
            length += len(word) + 1
    if current:
        lines.append(" ".join(current))
    return "\n".join(lines)


def build_report_pdf(report: ReportResponse) -> bytes:
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)  # A4
    margin = 56
    y = margin
    page_width = 595 - margin * 2

    def add_heading(text: str, size: int = 16) -> None:
        nonlocal y, page
        if y > 760:
            page = doc.new_page(width=595, height=842)
            y = margin
        safe = html.escape(text)
        box = fitz.Rect(margin, y, margin + page_width, y + 40)
        page.insert_htmlbox(
            box,
            f"<div dir='rtl' style='font-family:sans-serif;font-size:{size}pt;font-weight:bold;color:#001827'>{safe}</div>",
        )
        y += 34

    def add_paragraph(text: str, size: int = 11) -> None:
        nonlocal y, page
        wrapped = _wrap_lines(text, 88)
        lines = wrapped.split("\n")
        block_height = max(48, len(lines) * 16 + 12)
        if y + block_height > 800:
            page = doc.new_page(width=595, height=842)
            y = margin
        safe = html.escape(wrapped).replace("\n", "<br/>")
        box = fitz.Rect(margin, y, margin + page_width, y + block_height)
        page.insert_htmlbox(
            box,
            f"<div dir='rtl' style='font-family:sans-serif;font-size:{size}pt;line-height:1.6;color:#1a1a1a'>{safe}</div>",
        )
        y += block_height + 10

    add_heading(report.title, 20)
    add_paragraph(report.meta, 10)
    y += 6

    for section in report.sections:
        add_heading(section.title, 14)
        add_paragraph(section.body)
        y += 8

    add_heading("قائمة التحقق", 13)
    checklist = "\n".join(f"✓ {item}" for item in report.checklist)
    add_paragraph(checklist, 10)

    add_paragraph(
        f"درجة الثقة: {report.confidence}% · {report.compliant_title}",
        10,
    )

    footer = doc.new_page(width=595, height=842)
    footer.insert_text(
        (margin, 820),
        "Generated by RAGulator AI · LlamaIndex · Qdrant · FastEmbed · PyMuPDF",
        fontsize=9,
        color=(0.4, 0.4, 0.4),
    )

    buffer = BytesIO()
    doc.save(buffer)
    doc.close()
    return buffer.getvalue()


def save_report_pdf(report: ReportResponse, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(build_report_pdf(report))
    return path
