/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellWorkspaceRouteImport } from './routes/_shell.workspace'
import { Route as ShellReportRouteImport } from './routes/_shell.report'
import { Route as ShellIngestionRouteImport } from './routes/_shell.ingestion'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellWorkspaceRoute = ShellWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportRoute = ShellReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIngestionRoute = ShellIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof ShellDashboardRoute
  '/ingestion': typeof ShellIngestionRoute
  '/report': typeof ShellReportRoute
  '/workspace': typeof ShellWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof ShellDashboardRoute
  '/ingestion': typeof ShellIngestionRoute
  '/report': typeof ShellReportRoute
  '/workspace': typeof ShellWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/signin': typeof SigninRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/ingestion': typeof ShellIngestionRoute
  '/_shell/report': typeof ShellReportRoute
  '/_shell/workspace': typeof ShellWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/dashboard'
    | '/ingestion'
    | '/report'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/dashboard' | '/ingestion' | '/report' | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/signin'
    | '/_shell/dashboard'
    | '/_shell/ingestion'
    | '/_shell/report'
    | '/_shell/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/workspace': {
      id: '/_shell/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof ShellWorkspaceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/report': {
      id: '/_shell/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ShellReportRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ingestion': {
      id: '/_shell/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof ShellIngestionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellIngestionRoute: typeof ShellIngestionRoute
  ShellReportRoute: typeof ShellReportRoute
  ShellWorkspaceRoute: typeof ShellWorkspaceRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellIngestionRoute: ShellIngestionRoute,
  ShellReportRoute: ShellReportRoute,
  ShellWorkspaceRoute: ShellWorkspaceRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
